### ISSUE TITLE
problem with disable filter

### ISSUE THREAD

**Issue by mohsensd1373** [konvajs/ng2-konva#36]
Hi, I want to add a filter to the image and then delete the filter, but after deleting the image, the quality decreases.
this image show result 
[http://dls.kingblack.ir/files/problem%20konva.png](url)

**Comment by lavrton** [comment]
Make online demo. What extension of the image? SVG?

**Comment by mohsensd1373** [comment]
Thankful . I found the problem. When I called the image, it enlarged with the transformer, which made the image smaller, but the scale became larger, and when the filter on the image was canceled, the image quality remained in scale. Giving the correct image size according to the scale was solved.
